# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'NoBrokerBrowseAndFilter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NoBrokerBrowseAndFilter
  pod 'Alamofire', '~> 4.4'
  pod 'SDWebImage', '~> 4.0'

end
